### ISSUE TITLE
Update dependencies to support node 7 and 8

### ISSUE THREAD

**Issue by boblauer** [mongodb-js/version-manager#139]
Seeing this warning when running `npm install`:

```
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
```

The current dependency tree for `graceful-fs` is:

```
└─┬ mongodb-version-manager@1.0.7
  ├─┬ mongodb-download-url@0.1.10
  │ └─┬ mongodb-version-list@0.0.3
  │   └─┬ downcache@0.0.8
  │     └── graceful-fs@2.0.3
  └─┬ unzip@0.1.11
    └─┬ fstream@0.1.31
      └── graceful-fs@3.0.11
```

It looks like updating `mongodb-download-url` to the latest will pull in `graceful-fs@^4.1.3`, but `unzip@0.1.11` is a bit trickier because that project is abandoned.  However, there is a fork, https://www.npmjs.com/package/unzip-stream, that does have updated dependencies.

I would be happy to open a pull request myself if that would be desirable, but wanted to open an issue first either way.

**Comment by boblauer** [comment]
Sorry, meant to post this to the `mongodb-runner` repo.

**Comment by boblauer** [comment]
Sorry, closed this thinking I had created this issue in the wrong repo, but this is in fact the correct repo.

**Comment by imlucas** [comment]
should be sorted now
