### ISSUE TITLE
"mongodb-version-manager" = "m"?

### ISSUE THREAD

**Issue by nestorllamas** [mongodb-js/version-manager#153]
Hello,

I just want to know if the project `mongodb-verison-manager` is the same as the project `m` or not. Both are MongoDB version managers and use the command `m` at the beginning of the instructions (for example `m use <version>`).

Regards,
Néstor Llamas Llopis

**Comment by imlucas** [comment]
No, it's not. The plan originally was to consolidate the two projects (m doesn't support windows whereas version-manager does). However, it's been difficult to gather enough interest to make it happen :/ Neither of these are for use in a production environment... Only intended for development. I originally wrote version-manager so I could test Compass in CI against all different types of MongoDB deployments.

Use the official process https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/ to make sure your upgrades/version changes are processed correctly.

**Comment by nestorllamas** [comment]
Why do you say both version managers are not for production environment? What's the reason?

**Comment by nestorllamas** [comment]
testing...
